name: Hocoslamfy

on: [push]

jobs:
  build:
    name: Build Hocoslamfy
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: ['lepus', 'gcw0', 'rs90']
    container:
      image: ghcr.io/arcnor/toolchain-opendingux/${{ matrix.target }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make opk
      env:
        TARGET: hocoslamfy-${{ matrix.target }}
    - uses: actions/upload-artifact@v2
      with:
        name: hocoslamfy-${{ matrix.target }}
        path: |
          hocoslamfy-${{ matrix.target }}.opk
